debug: false
seed: 42
evaluation_mode: global
work_dir: ${hydra:runtime.cwd}
outputs_dir: ${hydra:runtime.output_dir}
wandb:
  active: true
  project: actuator_modeling_gru_v2
  entity: ''
  name_suffix: pure_gru_loss_diff_max_vel
  group_suffix: initial_tests
  watch_log_freq: 100
data:
  _target_: src.data.datamodule.ActuatorDataModule
  data_base_dir: data/real
  inertia_groups:
  - id: pos_A_300g
    folder: new_pos_A_300g_data
  - id: pos_C_300g
    folder: new_pos_C_300g_data
  - id: pos_D_300g
    folder: new_pos_D_300_g_data
  - id: pos_E_300g
    folder: new_pos_E_300g_data
  - id: no_mass
    folder: new_no_mass_data
  global_train_ratio: 0.7
  global_val_ratio: 0.15
  batch_size: 256
  num_workers: 4
  radius_accel: 0.03
  filter_cutoff_freq_hz: 30.0
  filter_order: 6
  sequence_duration_s: 1.0
  resampling_frequency_hz: 240.0
  max_torque_nm: 3.6
  sensor_biases:
    acc_y_bias: 0.039204
    gyro_z_bias: -0.002273
  max_commanded_vel: 10.0
model:
  model_type:
    name: gru
  _target_: src.models.model.ActuatorModel
  learning_rate: 0.001
  weight_decay: 1.0e-06
  warmup_epochs: 1
  use_residual: false
  k_spring: 0.1
  theta0: 0.0
  kp_phys: 4.0
  kd_phys: 0.04
  pd_stall_torque_phys_training: 1.8
  pd_no_load_speed_phys_training: 30.0
  loss_diff_weight: 0.1
  gru_hidden_dim: 128
  gru_num_layers: 2
  gru_dropout: 0.1
train:
  model: ../model/default.yaml
  data: ../data/actuator_data.yaml
  batch_size: ${data.batch_size}
  learning_rate: ${model.learning_rate}
  weight_decay: ${model.weight_decay}
  max_epochs: 200
  patience: 20
  num_workers: 4
  log_frequency: 50
  val_check_interval: 1.0
  wandb:
    project_name: actuator-modeling
  accelerator: auto
  devices: 1
  precision: 32-true
  early_stopping:
    active: true
    monitor: val_rmse_epoch
    mode: min
    patience: 10
    min_delta: 0.0001
    verbose: true
    stopping_threshold: null
  checkpointing:
    monitor: val_rmse_epoch
    mode: min
    save_top_k: 1
    filename: best_model-{epoch:02d}-{val_rmse_epoch:.4f}
  deterministic_trainer: true
  gradient_clip_val: 5.0
  gradient_clip_algorithm: norm
  callbacks:
    learning_rate_monitor: true
    early_summary: false
    test_prediction_plotter: true
  export_jit_model: true
