x-default-mars-jumper-environment: &default-mars-jumper-environment
  - OMNI_KIT_ALLOW_ROOT=1

x-default-mars-jumper-deploy: &default-mars-jumper-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  mars-jumper-daniel:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACLAB_BASE_IMAGE_ARG=${ISAACLAB_BASE_IMAGE}
        - DOCKER_MARS_JUMPER_PATH_ARG=${DOCKER_MARS_JUMPER_PATH}
    image: mars-jumper
    container_name: mars-jumper-daniel
    volumes:
      - type: bind
        source: ../
        target: ${DOCKER_MARS_JUMPER_PATH}
    network_mode: host
    environment: *default-mars-jumper-environment
    deploy: *default-mars-jumper-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true

  mars-jumper-johannes:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACLAB_BASE_IMAGE_ARG=${ISAACLAB_BASE_IMAGE}
        - DOCKER_MARS_JUMPER_PATH_ARG=${DOCKER_MARS_JUMPER_PATH}
    image: mars-jumper
    container_name: mars-jumper-johannes
    volumes:
      - type: bind
        source: ../
        target: ${DOCKER_MARS_JUMPER_PATH}
    networks:
      - simnet # This is one you need to make yourself
    environment: *default-mars-jumper-environment
    deploy: *default-mars-jumper-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true

networks: 
  simnet:
    name: simnet
    external: true
